[pytest]
# Parametro para definir los archivos que se van a ejecutar (todos "test_")
python_files= test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=report.html --self-contained-html
markers =
    smoke: pruebas criticas del sistema
    regression: pruebas de regresion
    api: pruebas de api
    ui: pruebas de interfaz